config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [ :index, :show ] do
    resources :comments, only: :create
  end

  # get '/events/new', to: 'courses#show'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'courses#index'
  resources :courses do

     resources :events do
       resources :hole_scores, only: [:create]
       resources :orders, only: [:show, :create] do
         resources :payments, only: [:new, :create]
       end
     end
     get 'dashboard', to: 'courses#dashboard', as: "course_dashboard"

  end


  resources :courses, only: [ :index, :show ] do
    resources :reviews, only: :create
  end


  resources :users do
    get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  end
  patch "users/:id", to: "user#update"

  resources :orders, only: :show do
    resources :payments
    post 'orders/:order_id/split', to: 'payments#split', as: 'split'
  end

  resources :users

  resources :friend_requests, only: [:index, :create, :update, :destroy] do
    resources :friendships, only: [:create]
  end
  # API ROUTES:
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index, :show ]
      resources :courses, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # this for events thing
  has_many :invites
  has_many :events
  has_many :comments
  has_many :invited_events , through: :invites, source: :events
  has_many :courses
  has_many :hole_scores
  has_many :reviews
  has_many :notifications

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  # validates :gender, presence: true

  # friendship
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, foreign_key: :friend_id
  # requests that the user received
  has_many :friend_requests, foreign_key: :friend_id, dependent: :destroy
  # requests that the user sent
  has_many :pending_friend_requests, class_name: 'FriendRequest', dependent: :destroy, foreign_key: :user_id
  # friends who haven't accepted the user request yet
  has_many :pending_friends, through: :pending_friend_requests, source: :friend


# search stuff
include PgSearch
  pg_search_scope :search_by_fullname, against: [ :first_name, :last_name]

  #API TOKEN:
  acts_as_token_authenticatable
  # this for uploading profile pic
  mount_uploader :photo, PhotoUploader

  # this for fb login
  devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def name
    "#{first_name} #{last_name}"
  end


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :set_user, only: [ :show ]
  def index
    @users = policy_scope(User)
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_after_action :verify_policy_scoped, only: [:index]
  def index
    if params[:search].present?
      @users = User.search_by_fullname(params[:search])
      @users = User.all.where.not(id: current_user.id) if @users.empty?
    else
      @users = User.all.where.not(id: current_user.id)
    end
  end

  def dashboard
    @user = User.find(params[:user_id])
    authorize @user
    @events = @user.events

    if current_user
      @friends = @user.friends
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    @events = @user.events.order(timeslot: :desc)

    if current_user
      @friends = @user.friends
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)

  end

  def destroy
    @user = User.new
  end

  private

  def user_params
  params.require(:user).permit(:first_name, :last_name, :email, :gender, :admin, :photo, :photo_cache, :address, :description, :favourite_course)
  end
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/dashboard.html.erb
<% profile_image_url = @user.facebook_picture_url || @user.photo.url || "http://placehold.it/110x110" %>


<div class="container-fluid">
  <div class="row user-dashboard">
    <div class="user--profile-info-container col-xs-12 col-md-3">
        <div class="user--profile-info">
          <div class="user--profile-info__avatar">
            <%= image_tag profile_image_url %>
            <h3>
              User Dashboard <%= @user.first_name %> <%= @user.last_name %>
            </h3>
          </div>
          <div class="user--profile-info__details">
            <p><i class="fa fa-envelope-o"></i> <%= @user.email %></p>
            <p><i class="fa fa-map-marker"></i> <%= @user.location? ? @user.location : 'No location to show' %></p>
            <% if @user == current_user  %>
            <%= link_to 'Edit your profile', edit_user_path(current_user) %>
            <% end %>
          </div>
          <div class="user--profile-info__friends">
            <h5>Friends</h5>
            <%  @friends.each do |friend| %>
               <% friend_image_url = friend.facebook_picture_url || friend.photo.url || "http://placehold.it/50x50" %>
              <%= link_to user_path(friend) do %>
                <%= image_tag friend_image_url %>
              <% end %>
            <% end %>
            <div class="user--friends-count">
              <p>
                <%= @friends.count %> Friends
              </p>
              <% if @user != current_user %>

                <a style="background-color: red;" href="#"><i class="fa fa-plus"></i>Add as a friend</a>
              <% end %>
            </div>
          </div>
        </div>
    </div>

    <div class="user--events-container col-xs-12 col-md-9">
      <div class="user--events">
        <h1>Upcoming Events</h1>
        <% @events.each do |event| %>
        <% if event.invited_users.index(current_user)  %>
          <%= render 'shared/dashboard_event', event: event, friends: @friends %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 login-form-container">
      <h2 class="text-center">Edit User Profile</h2>
      <%= simple_form_for @user, method: :patch do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :first_name, required: true, autofocus: true, placeholder: "John" %>
          <%= f.input :last_name, required: true, autofocus: true, placeholder: "Smith"%>
          <%= f.input :photo, label: false, label: "Upload a profile photo" %>
          <%= f.input :description, autofocus: true, label: "Tell us bit about yourself", placeholder: "Amateur golfer looking for buddies." %>
          <%= f.input :location, autofocus: true, label: "Where are you based?", placeholder: "London" %>
          <%= f.input :favourite_course, autofocus: true, label: "Where do you like to play?", placeholder: "London Golf Club" %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Update User Profile", class:"btn btn-gray" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/friends.html.erb
<div class="user-container">
  <%= render 'shared/user' %>
  <div class="friends-list-container">
    <h1>My Friends</h1>
    <div class="friend-container">
      <img class="avatar-small" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
      <p>Gab Dehan</p>
    </div>
    <div class="friend-container">
      <img class="avatar-small" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
      <p>Gab Dehan</p>
    </div>
    <button>Add friends through Facebook</button>

  </div>
</div>

app/views/users/index.html.erb
<%= render "shared/user" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% profile_image_url = @user.facebook_picture_url || @user.photo.url || "http://placehold.it/110x110" %>


<div class="container-fluid">
  <div class="row user-dashboard">
    <div class="user--profile-info-container col-xs-12 col-md-3">
        <div class="user--profile-info">
          <div class="user--profile-info__avatar">
            <%= image_tag profile_image_url %>
            <h3>
              <%= @user.first_name %> <%= @user.last_name %>
            </h3>
          </div>
          <div class="user--profile-info__details">
            <p><i class="fa fa-envelope-o"></i> <%= @user.email %></p>
            <p><i class="fa fa-map-marker"></i> <%= @user.location? ? @user.location : 'No location to show' %></p>
            <% if @user == current_user  %>

            <%= link_to 'Edit your profile', edit_user_registration_path %>

            <% end %>
          </div>
          <div class="user--profile-info__friends">
            <h5>Friends</h5>
            <%  @friends.each do |friend| %>
               <% friend_image_url = friend.facebook_picture_url || friend.photo.url || "http://placehold.it/50x50" %>
              <%= link_to user_path(friend) do %>
                <%= image_tag friend_image_url %>
              <% end %>
            <% end %>
            <div class="user--friends-count">
              <p>
                <%= @friends.count %> Friends
              </p>
              <% if @user != current_user %>
                <% friendship = Friendship.find_by(user_id: @user.id, friend_id: current_user.id) || Friendship.find_by(user_id: current_user.id, friend_id: @user.id) %>
                <% friendship_request = FriendRequest.find_by(user_id: @user.id, friend_id: current_user.id) || FriendRequest.find_by(user_id: current_user.id, friend_id: @user.id) %>
                <% if friendship_request  %>
                  <% if friendship_request.status == 'pending' %>
                  <a href="#">Pending <i class="fa fa-check"></i></a>
                  <% else %>
                  <a href="#">Friends <i class="fa fa-check"></i></a>
                  <% end %>
                <% else %>
                  <%= link_to friend_requests_path(user_id: @user.id), method: :post, class:"btn btn-pay-all" do %>
                    <i class="fa fa-plus"></i> Add friend
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
    </div>

    <div class="user--events-container col-xs-12 col-md-9">
      <div class="user--events">
        <h1>Events</h1>
        <% @events.each do |event| %>
        <% if event.invited_users.index(current_user)  %>
          <%= render 'shared/dashboard_event', event: event, friends: @friends %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>