config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [ :index, :show ] do
    resources :comments, only: :create
  end

  # get '/events/new', to: 'courses#show'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'courses#index'
  resources :courses do

     resources :events do
       resources :hole_scores, only: [:create]
       resources :orders, only: [:show, :create] do
         resources :payments, only: [:new, :create]
       end
     end
     get 'dashboard', to: 'courses#dashboard', as: "course_dashboard"

  end


  resources :courses, only: [ :index, :show ] do
    resources :reviews, only: :create
  end


  resources :users do
    get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  end
  patch "users/:id", to: "user#update"

  resources :orders, only: :show do
    resources :payments
    post 'orders/:order_id/split', to: 'payments#split', as: 'split'
  end

  resources :users

  resources :friend_requests, only: [:index, :create, :update, :destroy] do
    resources :friendships, only: [:create]
  end
  # API ROUTES:
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index, :show ]
      resources :courses, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_one :order
  has_many :invites, dependent: :destroy
  has_many :invited_users, through: :invites, source: :user
  has_many :comments, dependent: :destroy
  validates :timeslot, presence: true
  monetize :balance_cents
end

app/views/shared/_banner.html.erb
<div class="banner">
  <h1 class="homepage--header">Play together Play Better</h1>
  <%= render 'shared/searchbar', page: 'home' %>
</div>

app/views/shared/_course_badges.html.erb
<% if course.size %>
<div class="badge-pair col-xs-12 col-md-6 col-lg-4">
  <p><div class="hexagon"></div> <span><%= course.size.capitalize %> Sized</span></p>
</div>
<% end %>
<% if course.sand %>
  <div class="badge-pair col-xs-12 col-md-6 col-lg-4">
    <p>
      <div class="hexagon sand-badge"></div>
       <span>Sand</span>
     </p>
  </div>
<% end %>

<% if course.water %>
  <div class="badge-pair col-xs-12 col-md-6 col-lg-4">
    <p>
      <div class="hexagon water-badge"></div>
      <span>Water</span></p>
  </div>
<% end %>

<% if course.trees %>
  <div class="badge-pair col-xs-12 col-md-6 col-lg-4 ">
    <p><div class="hexagon trees-badge"></div> <span>Trees</span></p>
  </div>
<% end %>

<% if course.plain %>
  <div class="badge-pair col-xs-12 col-md-6 col-lg-4">
    <p><div class="hexagon"></div> <span><%= course.plain ? 'Plain Terrain' : 'Mountains'  %></span></p>
  </div>
<% end %>

app/views/shared/_course_card.html.erb
<% if course.image? %>
  <% url = cl_image_path course.image, height: 300, width: 400, crop: :fill %>
<% else %>
  <% url = image_path "banner-background.png" %>
<% end %>

<div class="col-xs-12 col-md-6 col-lg-4">
<div class="card" >
  <%= link_to course_path(course) do %>
  <div class="card-background" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url %>');">
    <div class="card-overlay">
      <h2><%= course.name %></h2>
      <p><%= course.address %></p>
    </div>

  </div>
  <% end %>

  <div class="card-info">

    <div class="card-options">
      <div class="card-options_top">
        <div class="rating">
          <% if Review.where(course_id: course.id) %>
          <% average_rating = Review.where(course_id: course.id).average(:rating).to_i # average_rating == course.average_rating %>
          <% else %>
          <% average_rating = 0 %>
          <% end %>
          <% average_rating.times do %>
            <i class="fa fa-star"></i>
          <% end %>
          <% (5 - average_rating).times do  %>
            <i class="fa fa-star-o"></i>
          <% end %>
        </div>
        <div class="price tag tag__green">$ <%= course.price.to_i %></div>
      </div>

      <div class="card-badges">
        <div class="hexagon"></div>
        <div class="hexagon"></div>
        <div class="hexagon"></div>
        <div class="hexagon"></div>
        <div class="hexagon"></div>
      </div>
    </div>

    <div class="card-book-now">
      <%= link_to course_path(course) do %>
      <p>Book now</p>
      <% end %>
    </div>
  </div>

</div>
</div>

app/views/shared/_course_card_draft.html.erb
<% if course.image? %>
  <% url = cl_image_path course.image, height: 300, width: 400, crop: :fill %>
<% else %>
  <% url = image_path "banner-background.png" %>
<% end %>

<div class="col-xs-12 col-sm-6 col-lg-4">
    <%= link_to course_path(course) do %>
    <div class="card2">
      <div class="card--background" style="background-image: url('<%= url %>');">
        </div>
        <div class="course-card-details">
        <h2><%= course.name %></h2>
        <div class="course-rating-badges">
          <div class="rating">
            <% if Review.where(course_id: course.id) %>
            <% average_rating = Review.where(course_id: course.id).average(:rating).to_i # average_rating == course.average_rating %>
            <% average_rating.times do %>
              <i class="fa fa-star"></i>
            <% end %>
            <% (5 - average_rating).times do  %>
              <i class="fa fa-star-o"></i>
              <% end %>
            <% end %>
          </div>
          <div class="badges-card">
            <% if course.size %>
            <div class="hexagon card-badge size-badge"></div>
            <% end %>
            <% if course.water %>
            <div class="hexagon card-badge water-badge"></div>
            <% end %>
            <% if course.sand %>
            <div class="hexagon card-badge sand-badge"></div>
            <% end %>
            <% if course.trees %>
            <div class="hexagon card-badge trees-badge"></div>
            <% end %>
            <% if course.plain %>
            <div class="hexagon card-badge plain-badge"></div>
            <% end %>
          </div>
        </div>
        <div class="flex">
          <div class="seventy-flex"></div>
          <div class="price tag tag__green">£ <%= course.price.to_i %>
          </div>
        </div>
        <p><i class="fa fa-map-marker"></i> <%= course.address %></p>
      </div>
    </div>
    <% end %>
</div>

app/views/shared/_course_dashboard_sidepanel.html.erb
<%= simple_form_for [@course], html: { class: "dashboard-sidepanel"}  do |f| %>
  <div class="recap--container">
    <h1>Your course settings:</h1>

    <div class="recap--container__details">
      <div class="recap-details-box">
        <p class="recap-label">invite your friends:</p>
        <div class="recap-invites">
        </div>

      </div>
      <div class="recap-details-box">
        <p class="recap-label">date:</p>

        <div class="form-group">
          <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control" name="event[timeslot]"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

    </div>
    <%= f.submit "confirm", :class => 'recap-btn-confirm' %>
  </div>
<% end %>

<%= content_for(:after_js) do%>
  <script>
  $(function () {

    $('#datetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      minDate: new Date(),
      defaultDate: new Date(),
      sideBySide: true,
      // inline: true
    });
  });
  </script>
<% end %>

app/views/shared/_course_show_recap.html.erb
<%= simple_form_for [@course, @event] do |f| %>
  <div class="recap--container">
  <% if current_user %>

    <h1>your booking:</h1>

    <div class="recap--container__details">
      <div class="recap-details-box">
        <p class="recap-label">invite your friends:</p>
        <div class="recap-invites">
        </div>
          <div class="event-checkbox-container">

            <% @friends.each do |friend| %>
            <% image_url = friend.facebook_picture_url || friend.photo.url || "http://placehold.it/60" %>
            <div class="form-group check_boxes optional event_invited_users">
              <span class="checkbox">
                <label for="event_invited_user_ids_<%= friend.id %>">
                  <input class="check_boxes optional hidden event-checkbox" type="checkbox" value="<%= friend.id %>" name="event[invited_user_ids][]" id="event_invited_user_ids_<%= friend.id %>">
                  <%= image_tag image_url, class: 'event-checkbox-label' %>
                </label>
              </span>
            </div>
            <% end %>
        </div>
      </div>
      <div class="recap-details-box">
        <p class="recap-label">Date & Time:</p>

        <div class="form-group">
          <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control recap-datetimepicker" name="event[timeslot]"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="recap-details-box price-box">
        <div class='recap-details-price'>
        <p class="price-label">Price per person:</p>
          <p>£ <%= @course.price%></p>
        </div>
        <div class='recap-details-price'>
        <p class="price-label">Total price:</p>
          <p class="total-price">£ <%= @course.price %></p>
        </div>
      </div>
    </div>
    <%= f.submit "confirm", :class => 'recap-btn-confirm' %>
    <% else %>
    <div class="recap--container__details">
      <div class="recap-details-box">
        <p class="recap-label">date:</p>
        <div class="form-group">
          <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control recap-datetimepicker" name="event[timeslot]"/>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="recap-details-box">
        <div class='recap-details-price'>
        <p class="price-label">Price per person:</p>
          <p>£ <%= @course.price%></p>
        </div>
      </div>
    </div>
    <div class="recap-signin recap-btn-confirm">
      <%= link_to "Please Login", user_session_path , :class => 'recap-btn-confirm' %>
      <%= link_to "Or Signup", new_user_registration_path , :class => 'recap-btn-confirm' %>
    </div>
    <% end %>
  </div>
<% end %>

<%= content_for(:after_js) do%>
  <script>
  $(function () {
  var today = moment();
  var tomorrowAtEight = moment(today).add(1, 'days').set({'hour': 8, 'minute': 0})
    $('#datetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      minDate: tomorrowAtEight,
      defaultDate: tomorrowAtEight,
      sideBySide: true,
      stepping: 10,
      daysOfWeekDisabled:  <%= @course.disabled_days %>
    });
  });
  var totalPrice = document.querySelector('.total-price')
  var checkedBoxes = document.querySelectorAll('input[type="checkbox"]');

  checkedBoxes.forEach(function(box) {
    box.addEventListener('change', function() {
      var checkBoxCount = document.querySelectorAll('input[type="checkbox"]:checked').length;
      console.log(checkBoxCount);
      totalPrice.innerText = '£ '+ <%= @course.price.to_i %> *  (checkBoxCount + 1);
    })
  })

  </script>
<% end %>

app/views/shared/_dashboard_event.html.erb
<%= link_to event_path(event) do %>
  <div class="event">
    <% event_image = event.course.image? ? event.course.image : 'http://placehold.it/200/4caf50/ffffff' %>
    <%= cl_image_tag event_image %>
    <div class="event--details">
      <div class="event--details__left">
        <p class="event--details__title"><%= event.title %></p>
        <p class="<%= event.timeslot.to_date.future? ? 'future-event' : 'past-event' %>"><%= event.timeslot.strftime('%A, %d %b - %H:%M')  %></p>
        <p><i class="fa fa-map-marker"></i> <%= event.course.address %></p>
        <div class="event--details__friends">

          <% event.invited_users.each do |u| %>
            <% friend_image_url = u.facebook_picture_url || u.photo.url || "http://placehold.it/50x50" %>
            <%= link_to user_path(u) do %>
              <%= image_tag friend_image_url %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="event--details__right">
        <div class="event--details__payment">
          <% if event.timeslot.to_date.future? %>
          <p>Pay now:</p>
            <% btn_pay_class = event.invites.where(user_id: current_user.id).first.status == 'paid' ? 'btn-paid' : 'btn-to-pay' %>
            <div class="btn btn-pay <%= btn_pay_class %> ">
              <% if event.invites.where(user_id: current_user.id).first.status == 'payment-pending' %>
                <i class="fa fa-credit-card" aria-hidden="true"></i>
              <% elsif event.invites.where(user_id: current_user.id).first.status == 'paid' %>
                <i class="fa fa-check" aria-hidden="true"></i>
              <% end %>
            <% else %>
            <%= link_to 'Check your previous scores', course_event_path(event.course, event) , class: 'btn btn-pay-all color-white'%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_dropdown_notification.html.erb
<% if n.event_id != nil %>
  <li>
    <div class="notification-body">
      <%= link_to event_path(n.event) do  %>
      <p><%= n.event.user.first_name %> invited you to <span class="notification-event-title"><%= n.event.title %></span>

    </div>
         <span class="notification-moment"> - <%= time_ago_in_words(n.created_at) %> ago.</span></p>
    <% end %>
  </li>

<% else %>

  <li>
    <div class="notification-body">
      <%= link_to user_path(FriendRequest.find(n.friend_request_id).user) do %>
      <p><%= FriendRequest.find(n.friend_request_id).user.first_name %>
        <% end %>
        <span class="notification-friend-request"> sent you a friend request</span>
        <%= link_to friend_request_friendships_path(n.friend_request_id), method: :post do %>
        <i class="fa fa-check accept-friend-request" aria-hidden="true"></i>
        <% end %>
        <%= link_to root_path do %>
        <i class="fa fa-times reject-friend-request" aria-hidden="true"></i>
        <% end %>
    </div>
    <span class="notification-moment"> - <%= time_ago_in_words(n.created_at) %> ago.</span>
  </p>
  </li>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= "transparent-navbar" if params[:controller] == 'courses' && params[:action] == 'index' %> ">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <div class="navbar-logo">
      <%= image_tag "logo.png" %>
      <h1 class="navbar-logo-name">Golf Pal</h1>

    </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <div class="input-group">
        <%= form_tag users_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder:" Search Friends", class:"search-friends"  %>
        <% end %>
      </div>
      <div class="navbar-wagon-item">
        <% unread = current_user.notifications.where(read: false).count %>
        <div class="dropdown">
          <i class="fa fa-bell <%= unread > 0 ? 'unread-notifications' : '' %>", data-toggle="dropdown"></i>
          <span data-toggle="dropdown" class="notification-count <%= unread > 0 ? 'unread-notifications' : '' %>"><%= unread %></span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu notification-dropdown">
              <% current_user.notifications.where(read: false).each do |n| %>
                <%= render 'shared/dropdown_notification', n: n %>
            <% end %>
          </ul>
        </div>
      </div>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || current_user.photo.url || "http://placehold.it/30x30" %>
<%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_dashboard_path(current_user) do %>
                <i class="fa fa-tachometer"></i>  <%= t(".settings", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path , method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <div class="btn btn-signup" data-toggle="modal" data-target="#signup">
        <p>Signup</p>
      </div>
      <div class="btn btn-login" data-toggle="modal" data-target="#login">
        <p>Login</p>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-bell"></i> <%= t(".profile", default: "Notifications") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-tachometer"></i>  <%= t(".settings", default: "Dashboard") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#", method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<!--Signup Modal -->
<div id="signup" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Signup</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :first_name, required: true %>
            <%= f.input :last_name, required: true %>
            <%= f.input :email, required: true, autofocus: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <!--<%= f.input :password_confirmation, required: true %>-->
            <%= f.input :photo %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Sign up", class:"btn btn-gray" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>



<!--Login Modal -->
<div id="login" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Signup</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true %>
            <%= f.input :password, required: false %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Login", class:"btn btn-gray" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_score_card.html.erb
<table class="table table-bordered table-condensed">
  <thead class="">
    <tr>
      <td>Hole</td>
      <td>Par</td>
      <% @event.invited_users.each do |user| %>
      <td><%= user.first_name %></td>
      <% end %>
    </tr>
  </thead>
  <tbody class="table table-striped">
    <% @course.holes.each_with_index do |hole, index| %>
      <tr>
        <th id="holen"><%= index+1 %></th>
        <td id="parn"><%= hole.par %></td>
        <% @event.invited_users.each do |user| %>
          <% hole_scores = user.hole_scores.where(hole_id: hole.id) %>
          <% if hole_scores.any? %>
            <% hole_scores.each do |hole_score| %>
              <td id="player-score" class="player-score <%= hole_score.strikes > hole_score.hole.par ? 'above-par' : 'below-par' %>"><%= hole_score.strikes %></td>
            <% end %>
          <% else %>
            <% hole_score = HoleScore.find_or_initialize_by(event: @event, user: user, hole: hole) %>
            <td class="player-scoren" id="hole-score-<%= user.id %>-<%= hole.id %>">
              <%= simple_form_for [@course, @event, hole_score], remote: true do |h| %>
              <%= h.input :strikes, label: false, class:"score-input" %>
              <%= h.input :user_id, as: :hidden %>
              <%= h.input :hole_id, as: :hidden %>
              <%= button_tag type: 'submit' do %>
                 <i class="fa fa-check" aria-hidden="true"></i>
              <% end %>
            <% end %>
            </td>

          <% end %>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_searchbar.html.erb
<%= form_tag courses_path, remote: true, class: 'form-inline search-form searchbar--home', method: :get do %>
  <div class="form-border">
    <%= text_field_tag :address, '', class: 'autocomplete_input form-control', placeholder: '' %>
  </div>
<% end %>


<% content_for(:after_js) do %>
  <script>
    var options = {
      strings: ["London", "Madrid", "Vicenza", "LeWagon", "Search"],
      loop: true,
      loopCount: 3,
      typeSpeed: 100,
      attr: 'placeholder'
    };



    $('.autocomplete_input').typed(options);





  </script>
<% end %>

app/views/shared/_user.html.erb
<div class="index-container">
<% @users.each do |u|%>

<div class="user--index-container col-xs-12 col-md-4">
    <div class="user--index-card">
      <div class="user--index-card__avatar">
        <%= image_tag u.facebook_picture_url || u.photo.url || "http://placehold.it/110x110" %>
      </div>
      <div class="user--index-card__details">
        <h5><%= u.first_name %> <%= u.last_name %></h5>
        <p><i class="fa fa-map-marker"></i> <%= u.location? ? u.location : 'No location to show' %></p>
        <% friendship = Friendship.find_by(user_id:u.id, friend_id: current_user.id) || Friendship.find_by(user_id: current_user.id, friend_id: u.id) %>
        <% friendship_request = FriendRequest.find_by(user_id: u.id, friend_id: current_user.id) || FriendRequest.find_by(user_id: current_user.id, friend_id: u.id) %>
        <% if friendship_request  %>
          <% if friendship_request.status == 'pending' %>
          <a href="#" class="btn btn-pending-friendship" style="color: #3D5AFE;border-color: #3D5AFE;">Pending <i class="fa fa-clock-o"></i></a>
          <% else %>
          <a href="#" class="btn btn-pending-friendship">Friends <i class="fa fa-check" ></i></a>
          <% end %>
        <% else %>
          <%= link_to friend_requests_path(user_id: u.id), method: :post, class:"btn btn-pay-all" do %>
            <i class="fa fa-plus"></i> Add friend
          <% end %>
        <% end %>
      </div>
    </div>
</div>

<% end %>
</div>

app/views/shared/_user_sidebar.html.erb
<% profile_image_url = @user.facebook_picture_url || @user.photo.url || "http://placehold.it/110x110" %>

<div class="user--profile-info-container col-xs-12 col-md-3">
    <div class="user--profile-info">
      <div class="user--profile-info__avatar">
        <%= image_tag profile_image_url %>
        <h3>
          <%= @user.first_name %> <%= @user.last_name %>
        </h3>
      </div>
      <div class="user--profile-info__details">
        <% if @user == current_user  %>
          <ul style="list-style: none;">
            <li>
            <p><i class="fa fa-envelope-o"></i> <%= @user.email %></p>
            </li>
            <li>
            <p><i class="fa fa-map-marker"></i> <%= @user.location? ? @user.location : 'No location to show' %></p>
            </li>
            <li>
            <%= link_to 'Profile', user_path(current_user) %>
            </li>
            <li>Notifications</li>
            <li>Friends</li>
            <li>Events</li>
            <li>
            <%= link_to 'Add a course', new_course_path %>
            </li>
            <li>
            <%= link_to 'Course settings', new_course_path %>
            </li>
            <li>Bookings</li>
            <li><%= link_to 'Settings', edit_user_registration_path %>
            </li>
          </ul>
        <% end %>
      </div>
      <div class="user--profile-info__friends">
        <h5><%= @friends.count %> Friends</h5>
        <%  @friends.each do |friend| %>
           <% friend_image_url = friend.facebook_picture_url || friend.photo.url || "http://placehold.it/50x50" %>
          <%= link_to user_path(friend) do %>
            <%= image_tag friend_image_url %>
          <% end %>
        <% end %>
        <div class="user--friends-count">
          <p>
            <% @friends.count %>
          </p>
          <% if @user != current_user %>
          <a href="#"><i class="fa fa-plus"></i>Add as a friend</a>
          <% end %>
        </div>
      </div>
    </div>
</div>