config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [ :index, :show ] do
    resources :comments, only: :create
  end

  # get '/events/new', to: 'courses#show'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'courses#index'
  resources :courses do

     resources :events do
       resources :hole_scores, only: [:create]
       resources :orders, only: [:show, :create] do
         resources :payments, only: [:new, :create]
       end
     end
     get 'dashboard', to: 'courses#dashboard', as: "course_dashboard"

  end


  resources :courses, only: [ :index, :show ] do
    resources :reviews, only: :create
  end


  resources :users do
    get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  end
  patch "users/:id", to: "user#update"

  resources :orders, only: :show do
    resources :payments
    post 'orders/:order_id/split', to: 'payments#split', as: 'split'
  end

  resources :users

  resources :friend_requests, only: [:index, :create, :update, :destroy] do
    resources :friendships, only: [:create]
  end
  # API ROUTES:
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index, :show ]
      resources :courses, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_one :order
  has_many :invites, dependent: :destroy
  has_many :invited_users, through: :invites, source: :user
  has_many :comments, dependent: :destroy
  validates :timeslot, presence: true
  monetize :balance_cents
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(user_id[current_user.id]).order
  end

  def show

     @event = Event.find(params[:id])
     @course = @event.course
     @order = Order.where(event_id: @event.id).first
     @invitees = @event.invited_users
     @comment = Comment.new
     notification = Notification.find_by(event_id: @event.id, user_id: current_user.id)
     if notification
       notification.update(read: true);
     end
     authorize @event
    #  @hole_score = HoleScore.new
  end

  def new
    @event = Event.new
  end

  def destroy
    @event = Event.destroy(params[:id])
    redirect_to events_path
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    authorize @event
  end

  def create
    @event = Event.new(event_params)

    @event.user = current_user
    @event.course = Course.find(params[:course_id])
    invites_names = "" # event title string with invites names
    if params[:event][:invited_user_ids]
      params[:event][:invited_user_ids].each do |id|
        invites_names += ", #{User.find(id).first_name}"
      end
    end
    @event.title = "#{@event.course.name} day with #{current_user.first_name}#{invites_names}"
    authorize @event
    if @event.save
      Invite.create(user: current_user, event: @event, status: 'payment-pending')
      unless params[:event][:invited_user_ids].nil?
        params[:event][:invited_user_ids].each do |id|
          Invite.create(user: User.find(id), event: @event, status: 'payment-pending')
          Notification.create(user: User.find(id), event: @event)
        end
      end
      @event.balance_cents = @event.course.price_cents * @event.invites.size
      @event.save

      @order = Order.create!(amount_cents: @event.balance_cents, sku: "#{@event.course.name.downcase.split(' ').join('-')}-#{@event.invited_users.size}-id:#{@event.id}", status: 'pending', event_id: @event.id)
      redirect_to course_event_path(@event.course, @event)
    else
      render :new
    end
    # # create event
    # new_event = Event.new(event_params)
    # new_event.user = current_user
    # new_event.course = Course.find(params[:course_id])
    # if !new_event.save
    #   redirect_to :back
    # end
    # #create invite
    # invites_array = []
    # new_invite_one = Invite.new(invite_one_params)
    # new_invite_one.event = new_event
    # invites_array << new_invite_one
    #
    # new_invite_two = Invite.new(invite_two_params)
    # new_invite_two.event = new_event
    # invites_array << new_invite_two
    #
    # new_invite_three = Invite.new(invite_three_params)
    # new_invite_three.event = new_event
    # invites_array << new_invite_three
    #
    # valid_array = []
    # invites_array.each do |i|
    #   valid_array << i if !i.user_id.nil?
    # end
    #
    # if valid_array.count > 0
    #   final_array = []
    #   valid_array.each do |i|
    #     final_array << i.save
    #   end
    # end
    #
    # if final_array.all?
    #
    #   redirect_to event_path(new_event)
    #
    # else
    #   redirect_to :back
    # end
  end

private

  def event_params
    params.require(:event).permit(:timeslot, :title, :balance)
  end


end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="user-container">
  <%= render 'shared/user' %>
  <div class="events-list-container">
    <h1>My Upcoming Events</h1>
    <div class="event-container hosting">
      <div class="event-date">
        <p>Tue 10th Oct</p>
        <p>10:00 am</p>
      </div>
      <div class="event-details">
        <p><b>Event Name (hosting)</b></p>
        <p>Golf course name</p>
        <p>Payment: complete</p>
      </div>
      <div class="guests">
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
      </div>
    </div>
   <div class="event-container">
      <div class="event-date">
        <p>Tue 10th Oct</p>
        <p>10:00 am</p>
      </div>
      <div class="event-details">
        <p><b>Event Name</b></p>
        <p>Golf course name</p>
        <p>Payment: incomplete</p>
      </div>
      <div class="guests">
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small to-pay"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small to-pay"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
      </div>
    </div>

    <h1>My Past Events</h1>
    <div class="event-container">
      <div class="event-date">
        <p>Tue 10th Oct</p>
        <p>10:00 am</p>
      </div>
      <div class="event-details">
        <p><b>Event Name</b></p>
        <p>Golf course name</p>
      </div>
      <div class="guests">
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small to-pay"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small to-pay"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
        <img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-small"/>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% if @event.timeslot.to_date.future? %>
<!-- <div class="container"> -->
<!--   <div class="row">
    <div class="col"> -->
      <div class="event-container">
        <div class="event-container-left">

          <%= render 'shared/event_banner', event: @event, course: @course %>
          <div class="event-box">
            <div class="event-guest">
              <div class="event-guest-name">
                <h3>Players</h3>
              </div>
              <div class="event-guest-pay">
                <% if @event.balance != 0 %>
                <p>£ <%= @event.balance %></p>
                <%= form_tag order_payments_path(@order) do %>
                  <%= hidden_field_tag 'event_id', @event.id %>
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-name="Book Golf Course"
                      data-email="<%= current_user.email %>"
                      data-description="Booking <%= @order.sku %>"
                      data-amount="<%= @event.balance_cents %>"
                      data-currency="<%= @order.amount.currency %>">

                      </script>
                      <%= button_tag(type: "submit", class: "btn btn-pay-all") do %>
                      <i class="fa fa-credit-card" aria-hidden="true"></i>  Pay All
                      <% end %>
                  <% end %>
                  <% else %>
                  <p class="btn btn-pay-all" style="cursor: default">All paid!</p>
                <% end %>
              </div>
            </div>


            <% @event.invites.each do |invite| %>
              <%= render 'shared/event_invite', invite: invite, event: @event %>
            <% end %>


          </div>
        </div>
        <div class="event-container-right">
          <div id="event-map"></div>
          <div class="event-box comments-box">
            <div class="comments-form">
              <h3 class="comments-number">
                <%= pluralize @event.comments.size, "Comment" %>
              </h3>
              <%= render 'comments/form', event: @event, comment: @comment  %>
            </div>
            <div id="comments">
              <% if @event.comments.blank? %>
                <!-- <p>Be the first to leave a comment</p> -->
              <% else %>
                <% @event.comments.reverse.each do |comment| %>
                  <%= render 'comments/show', comment: comment %>
                <% end %>
              <% end %>
            </div>

          </div>

        </div>
      </div>
      <% else %> <%# IF EVENT IS PAST  %>
      <div class="event-container">
        <div class="event-container-left event-past-container">
          <%= render 'shared/event_banner', event: @event, course: @course %>
        <div class="event-box">
          <h3>Scores</h3>
          <%= render 'shared/score_card' %>
        </div>
      </div>
    </div>
      <% end %>

<!--     </div>
  </div> -->
<!-- </div> -->

<% content_for(:after_js) do %>
  <script type="text/javascript">

  const styles = [
    {
        "featureType": "administrative.land_parcel",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "lightness": 20
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry",
        "stylers": [
            {
                "hue": "#f49935"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry",
        "stylers": [
            {
                "hue": "#fad959"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#a1cdfc"
            },
            {
                "saturation": 30
            },
            {
                "lightness": 49
            }
        ]
    }
  ];

  var handler = Gmaps.build('Google', { markers: { clusterer: undefined } });
    handler.buildMap({ provider: {styles: styles }, internal: { id: 'event-map' } }, function() {
      markers = handler.addMarkers(<%= raw [{lat: @event.course.latitude, lng: @event.course.longitude}].to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
       handler.getMap().setZoom(12);
    });

    document.querySelectorAll(".stripe-button-el").forEach(function(button) {
      button.style.display = 'none';
    })

  </script>

<% end %>